# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93841cae53334857e855e3dcd98f1b7c819f8ad099a0682add0724327ce8f54b085ac484604f27ff06e11f69cfe99156735bf1e2b14def3fdaf3a1a4b71919bf

test:
  secret_key_base: 5dc0bf961bc73ade008414fa26c82a2107ed19787fa25cdaa8a44df5d5472ea01f645a4a648ac79edc1d5e397b882e11f6918d3ee9031cc08f7dca12b004f318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
